require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sequel

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Rake/Desc:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
